name: "Publish GitHub Action"
on:
  push:
    branches:
      - master
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "test.json"
          json: '{"name":"json sucessfully created!"}'
      - run: sh ./test-json.sh
  publish:
    needs: [test-action]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: TG908/publish-github-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}